name: flutter_hsvcolor_picker_example
description: A new Flutter project.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hsvcolor_picker:
    path: ../

flutter:
  uses-material-design: true
  
  assets:
   - packages/avatar.jpg
