name: flutter_hsvcolor_picker_example
description: A new Flutter project.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hsvcolor_picker:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - packages/avatar.jpg
