name: flutter_hsvcolor_picker
description: A HSV color picker inspired by chrome devtools and a material color picker for your flutter app.
version: 1.5.0
homepage: https://github.com/fluttercandies/flutter_hsvcolor_picker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
